Check for bash 4.1+; note Qt 4.8+ in the readme (fixes #19).

diff --git a/qtah-generator/qtah-listener-gen b/qtah-generator/qtah-listener-gen
--- a/qtah-generator/qtah-listener-gen
+++ b/qtah-generator/qtah-listener-gen
@@ -17,6 +17,13 @@
 # You should have received a copy of the GNU Lesser General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+if (( BASH_VERSINFO[0] < 4 || ( BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 1 ) )); then
+    echo "qtah-listener-gen: Error, this script depends on features in bash 4.1 and newer." >&2
+    echo "qtah-listener-gen: You are currently running version $BASH_VERSION, please upgrade." >&2
+    echo "qtah-listener-gen: Aborting." >&2
+    exit 1
+fi
+
 set -euo pipefail
 
 msg() {
